name: Python package

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - run: ls -l dist
      - name: Upload wheel to artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
